import { expect, test, type Page } from "@playwright/test";

async function expectMcpSummary(page: Page) {
  await expect(
    page.getByText(/MCP 选择：(Linear MCP、Knowledge Index MCP|Knowledge Index MCP、Linear MCP)/),
  ).toBeVisible();
}

test("home and key flows render", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByText("先配置协作系统，再让不同 AI 客户端替你工作。")).toBeVisible();

  await page.goto("/onboarding");
  await expect(page.getByText("先收集最少但最有用的信息。")).toBeVisible();
  await page.getByLabel("你是谁").fill("独立开发者");
  await page.getByLabel("你最重要的目标").fill("建立统一 AI 协作底座");
  await page.getByLabel("你常用哪些 AI 客户端").fill("Codex、Cursor、ChatGPT");
  await page.getByLabel("你最常让 AI 帮你做什么").fill("写 PRD、拆需求、改代码、复盘");
  await page.getByLabel("你最担心 AI 出什么问题").fill("乱改文件、上下文不一致、做完没验证");
  await page.getByRole("button", { name: "生成诊断与推荐" }).click();
  await expect(page.getByText("你现在最需要的不是更多 prompt，而是一套统一协作规则。")).toBeVisible();
  await expect(page.getByText("独立开发者")).toBeVisible();
  await page.getByRole("link", { name: "进入配置流程" }).click();

  await expect(page.getByText("先给出一套默认推荐，再解释为什么。")).toBeVisible();
  await expect(page.getByText("建立统一 AI 协作底座")).toBeVisible();
  await expect(page.getByText("当前未接入任何 MCP，也可以继续使用 AI-OS、客户端适配文件和本地规则沉淀。")).toBeVisible();
  await expect(page.getByText("推荐起点")).toBeVisible();
  await expect(page.getByText("只建议")).toBeVisible();
  await expect(page.getByText("允许运行本地命令，但高风险动作仍需人工确认。")).toBeVisible();
  await expect(page.getByText("本地动作")).toBeVisible();
  await expect(page.getByText("真实世界动作")).toBeVisible();
  await expect(page.getByText("外部系统动作")).toBeVisible();
  const knowledgeIndexCheckbox = page.getByRole("checkbox", { name: "Knowledge Index MCP" });
  const linearCheckbox = page.getByRole("checkbox", { name: "Linear MCP" });
  await knowledgeIndexCheckbox.check();
  await linearCheckbox.check();
  await expect(knowledgeIndexCheckbox).toBeChecked();
  await expect(linearCheckbox).toBeChecked();
  await page.getByRole("button", { name: "继续生成 AI-OS" }).click();
  await expect(page.getByText("这是你的第一版 AI-OS，可直接作为后续项目的起点。")).toBeVisible();
  await expectMcpSummary(page);
  await expect(page.getByText("AI-OS/identity.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/clients/claude-code.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/clients/cursor.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/clients/copilot.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/mcp/selection.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/permissions/boundaries.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/adapter-setup.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/environment-check.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/existing-rules-scan.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/diff-merge-plan.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/sensitive-risk-guard.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/mcp-health.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/profile.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/profile.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/boundaries.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/boundaries.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/style-card.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/style-card.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/source-map.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/source-map.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/draft-context.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/draft-context.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-prompt.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-prompt.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-sample.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-sample.json").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/target-locations.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/install/verification-checklist.md").first()).toBeVisible();
  await expect(page.getByText("ContentOps Profile 映射")).toBeVisible();
  await expect(page.getByText("字段映射说明")).toBeVisible();
  await expect(page.getByText("Content Boundaries 注入")).toBeVisible();
  await expect(page.getByText("Boundary 字段说明")).toBeVisible();
  await expect(page.getByText("Style Card", { exact: true })).toBeVisible();
  await expect(page.getByText("Style 字段说明")).toBeVisible();
  await expect(page.getByText("Source Map", { exact: true })).toBeVisible();
  await expect(page.getByText("Source 字段说明")).toBeVisible();
  await expect(page.getByText("Draft Context Bundle", { exact: true })).toBeVisible();
  await expect(page.getByText("Draft Context 字段说明")).toBeVisible();
  await expect(page.getByText("Mother Draft Prompt", { exact: true })).toBeVisible();
  await expect(page.getByText("Prompt 字段说明")).toBeVisible();
  await expect(page.getByText("Mother Draft Sample", { exact: true })).toBeVisible();
  await expect(page.getByText("Sample 字段说明")).toBeVisible();
  await expect(page.getByText("定位陈述", { exact: true })).toBeVisible();
  await expect(page.getByText("目标受众", { exact: true })).toBeVisible();
  await expect(page.getByText("核心话题与内容支柱", { exact: true })).toBeVisible();
  await expect(page.getByText("positioning.positioningStatement", { exact: true })).toBeVisible();
  await expect(page.getByText("Hard Stops", { exact: true })).toBeVisible();
  await expect(page.getByText("Review Required", { exact: true })).toBeVisible();
  await expect(page.getByText("Injection Targets", { exact: true })).toBeVisible();
  await expect(page.getByText("boundaries.hardStops", { exact: true })).toBeVisible();
  await expect(page.getByText("Voice", { exact: true })).toBeVisible();
  await expect(page.getByText("Preferred Moves", { exact: true })).toBeVisible();
  await expect(page.getByText("ContentOps Use", { exact: true })).toBeVisible();
  await expect(page.getByText("voice.*", { exact: true })).toBeVisible();
  await expect(page.getByText("Pre-Draft Sources", { exact: true })).toBeVisible();
  await expect(page.getByText("Fallback Plan", { exact: true })).toBeVisible();
  await expect(page.getByText("contentOpsUse.preDraftSources", { exact: true })).toBeVisible();
  await expect(page.getByText("Draft Inputs", { exact: true })).toBeVisible();
  await expect(page.getByText("Draft Flow", { exact: true })).toBeVisible();
  await expect(page.getByText("Review Checklist", { exact: true })).toBeVisible();
  await expect(page.getByText("draftInputs.*", { exact: true })).toBeVisible();
  await expect(page.getByText("System Intent", { exact: true })).toBeVisible();
  await expect(page.getByText("Usage Notes", { exact: true })).toBeVisible();
  await expect(page.getByText("userPrompt", { exact: true })).toBeVisible();
  await expect(page.getByText("Title", { exact: true })).toBeVisible();
  await expect(page.getByText("Intro", { exact: true })).toBeVisible();
  await expect(page.getByText("Missing Evidence", { exact: true })).toBeVisible();
  await expect(page.getByText("missingEvidence", { exact: true })).toBeVisible();
  await expect(page.getByText("本地环境检测")).toBeVisible();
  await expect(page.getByText("已有规则识别与冲突扫描")).toBeVisible();
  await expect(page.getByText("配置 diff 预览与合并建议")).toBeVisible();
  await expect(page.getByText("敏感信息检查与风险提示")).toBeVisible();
  await expect(page.getByText("MCP 连接状态检测与失败兜底")).toBeVisible();
  await expect(page.getByText("任务后复盘", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "进入复盘" })).toBeVisible();
  await expect(page.getByText("这次任务是什么", { exact: true })).toBeVisible();
  await expect(page.getByText("这次什么做得好", { exact: true })).toBeVisible();
  await expect(page.getByText("这次哪里卡住了", { exact: true })).toBeVisible();
  await expect(page.getByText("哪些经验值得沉淀成规则", { exact: true })).toBeVisible();
  await expect(page.getByText("保存策略", { exact: true })).toBeVisible();
  await expect(page.getByText("规则候选生成与分类", { exact: true })).toBeVisible();
  await expect(page.getByText("把验证前置为共享边界")).toBeVisible();
  await expect(page.getByText("把任务后复盘固定进默认流程")).toBeVisible();
  await expect(page.getByText("记录本轮客户端与权限选择")).toBeVisible();
  await expect(page.getByRole("checkbox", { name: /把验证前置为共享边界/ })).toBeChecked();
  await expect(page.getByRole("checkbox", { name: /把任务后复盘固定进默认流程/ })).toBeChecked();
  await expect(page.getByRole("checkbox", { name: /记录本轮客户端与权限选择/ })).toBeChecked();
  await expect(page.getByText("确认保存规则", { exact: true })).toBeVisible();
  await expect(page.getByText("只有你勾选的候选会写回共享规则文件")).toBeVisible();
  await expect(page.getByText("rules").first()).toBeVisible();
  await expect(page.getByText("workflows").first()).toBeVisible();
  await expect(page.getByText("decisions").first()).toBeVisible();
  await expect(page.getByText(/来源：复盘字段/).first()).toBeVisible();
  await expect(page.getByText("AI-OS/templates/AGENTS.md.template").first()).toBeVisible();
  await expect(page.getByText("AI-OS/templates/cursor-project-rules.template.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/templates/claude-code-session-template.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/candidates/AGENTS.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/candidates/cursor-rules.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/candidates/project-root/AGENTS.md").first()).toBeVisible();
  await expect(page.getByText("AI-OS/candidates/.cursor/rules/ai-collab-foundation.mdc").first()).toBeVisible();
  await expect(page.getByText("AI-OS/candidates/claude-code/session-start.md").first()).toBeVisible();
  await expect(page.getByText("所有客户端共享同一套目标、角色、任务边界与输出标准。").first()).toBeVisible();
  await expect(page.getByText("# Identity").first()).toBeVisible();
  await expect(page.getByText("# ContentOps Profile")).toBeVisible();
  await expect(page.getByText("# Content Boundaries").first()).toBeVisible();
  await expect(page.getByText("# Style Card")).toBeVisible();
  await expect(page.getByText("# Source Map")).toBeVisible();
  await expect(page.getByText("# Draft Context Bundle")).toBeVisible();
  await expect(page.getByText("# Mother Draft Prompt Pack")).toBeVisible();
  await expect(page.getByText("# Mother Draft Sample")).toBeVisible();
  await expect(page.getByText("# Claude Code Client Profile")).toBeVisible();
  await expect(page.getByText("# Adapter Setup Guide")).toBeVisible();
  await expect(page.getByText("# MCP Selection").last()).toBeVisible();
  await expect(page.getByText("# Permission Boundaries")).toBeVisible();
  await expect(page.getByText("# Target Locations")).toBeVisible();
  await expect(page.getByText("# Verification Checklist")).toBeVisible();
  await expect(page.getByText("# AGENTS.md Template")).toBeVisible();
  await expect(page.getByText("# Cursor Project Rules Template")).toBeVisible();
  await expect(page.getByText("# Claude Code Session Template")).toBeVisible();
  await expect(page.getByText("# AGENTS.md").nth(1)).toBeVisible();
  await expect(page.getByText("# Cursor Rules")).toBeVisible();
  await expect(page.getByText("# AI Collab Foundation Cursor Rule").last()).toBeVisible();
  await expect(page.getByText("# Claude Code Session Start").last()).toBeVisible();
  await expect(page.getByText("# Rules")).toBeVisible();
  await page.getByRole("button", { name: "写出 AI-OS 文件" }).click();
  await expect(page.getByText("AI-OS 已写出到本地目录")).toBeVisible();
  await expect(page.getByText("本次已确认保存：")).toBeVisible();
  await expect(page.getByText("规则轻量版本记录", { exact: true })).toBeVisible();
  await expect(page.getByText(/当前版本：/)).toBeVisible();
  await expect(page.getByText(/保存时间：/)).toBeVisible();
  await expect(page.getByText("客户端同步提示", { exact: true })).toBeVisible();
  await expect(page.getByText(/Codex\s*->\s*AGENTS\.md/)).toBeVisible();
  await expect(page.getByText(/Cursor\s*->\s*\.cursor\/rules\/ai-collab-foundation\.mdc/)).toBeVisible();
  await expect(page.getByText(/Claude Code\s*->\s*AI-OS\/candidates\/claude-code\/session-start\.md/)).toBeVisible();
  await expect(page.getByText(/把验证前置为共享边界/).last()).toBeVisible();
  await expect(page.getByText(/generated-ai-os/)).toBeVisible();
  await page.goto(`/setup-check?role=${encodeURIComponent("独立开发者")}&goal=${encodeURIComponent("建立统一 AI 协作底座")}&clients=${encodeURIComponent("Codex、Cursor、ChatGPT")}&tokenStatus=${encodeURIComponent("need-token")}&tasks=${encodeURIComponent("写 PRD、拆需求、改代码、复盘")}&concerns=${encodeURIComponent("乱改文件、上下文不一致、做完没验证")}&mcpSelection=${encodeURIComponent("Linear")}&mcpSelection=${encodeURIComponent("Knowledge Index")}`);
  await expect(page.getByText("接入之后，应该如何确认这套底座真的生效了。")).toBeVisible();
  await expectMcpSummary(page);
  await expect(page.getByText("当前接入阶段")).toBeVisible();
  await expect(page.getByText("本地环境健康检查")).toBeVisible();
  await expect(page.getByText("已有规则识别与冲突扫描")).toBeVisible();
  await expect(page.getByText("配置 diff 预览与合并建议")).toBeVisible();
  await expect(page.getByText("敏感信息检查与风险提示")).toBeVisible();
  await expect(page.getByText("MCP 连接状态检测与失败兜底")).toBeVisible();
  await expect(page.getByText("ContentOps 联动产物检查")).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-prompt.md").last()).toBeVisible();
  await expect(page.getByText("AI-OS/contentops/mother-draft-sample.md").last()).toBeVisible();
  await expect(page.getByText("已导出但未放置")).toBeVisible();
  await expect(page.getByText("已放置待验证")).toBeVisible();
  await expect(page.getByText("已接入可使用")).toBeVisible();
  await expect(page.getByText("Codex 放置与验证")).toBeVisible();
  await expect(page.getByText("Claude Code 放置与验证")).toBeVisible();
  await expect(page.getByText("Cursor 放置与验证")).toBeVisible();
  await expect(page.getByText("客户端同步提示", { exact: true })).toBeVisible();
  await expect(page.getByText("收尾验收标准：复盘入口已存在")).toBeVisible();
  await expect(page.getByText("# Target Locations")).toBeVisible();
  await expect(page.getByText("# Verification Checklist")).toBeVisible();
});
